### ISSUE TITLE
"report server refused to connect" I'm getting this error and browser console print that it is due to X-Frame-Options set to same origin . Please help me to solve this issue.

### ISSUE THREAD

**Issue by Gaurangs** [tycomo/ngx-ssrs-reportviewer#34]

**Comment by akshayG14** [comment]
Even when I tried the package, was facing the same issue. Found out that I was trying to render the report using the file URL instead of the one retrieved from the report server. This is not a issue caused by the package, but rather the implementation of the report fetch. Update the server and report path to the one provided by the report server and it should resolve the issue.

**Comment by Gaurangs** [comment]
Thanks Akshay for your help :) It worked.
